extern UBYTE labels[15][32];
extern UBYTE *Sct;
extern struct Node List1Nodes[];
extern struct Node Cargo3Nodes[];
extern UBYTE InfoWdt[];
extern struct class class[];
extern STRPTR error, proceed, information;
extern STRPTR firstnames[], lastnames[], types[];
extern struct Image *citypanelimage, *shipviewimage, *classimage;
extern struct Image *shipimage[];
extern struct RastPort hidden_rp;
extern struct BitMap *hidden_bm;
extern struct Node *nodelist;
extern struct Node dockednodes[];
extern struct Node freecabinsnode;
extern struct ship *shiplist, *ship, *currentship, *first, *second, *shipa,
    *shipb;
extern struct person *personlist, *person, *currentperson;
extern struct city *currentcity;
extern ULONG gametime, money, hour;
extern UWORD ships, howmuch, shipnum, selected, shipclass, namesleft, persons;
extern WORD citydiff[][12];
extern UBYTE text[][36];
extern BYTE cargotype[][12];
extern UBYTE latitude[], longitude[], datestr[], shipnums[], dockstring[],
    freecabinstext[], price[], citiesknown[];
extern UBYTE *map;
extern WORD mapleft, maptop, reputation;
extern UBYTE autocenter, cargonum, transfermode, transfernum, peoplemode,
    textx, texty, shippeople, cityn, shipturn, infomode, skipflag, cheatmode,
    fastautopilot;
extern BYTE currentdockedship;
extern double increment, slowest;
extern APTR logfile;

extern void setshiplocation(struct ship *, UWORD, UWORD);
extern void getshiplocation(struct ship *, UWORD *, UWORD *);
extern UWORD getshipimage(UBYTE, UBYTE, UBYTE, UBYTE);
extern struct ship *createship(STRPTR, UBYTE);
extern void deleteship(struct ship *);
extern void freeships();
extern struct person *createperson(UWORD, ULONG, struct city *, UBYTE, UBYTE);
extern void settype(struct person *, UBYTE);
extern UBYTE gettype(struct person *);
extern void setloc(struct person *, UWORD);
extern UWORD getloc(struct person *);
extern void setmark(struct person *, UWORD);
extern UWORD getmark(struct person *);
extern void addperson(struct person *);
extern void createpassenger();
extern void createcrew();
extern void freeperson(struct person *);
extern void freepersons();
extern void createpersonlist(struct MinList *, void *, UBYTE);
extern struct person *findperson(void *, LONG, UBYTE);
extern ULONG rfindperson(void *, struct person *, UBYTE);
extern void showperson(struct person *);
extern void select(struct ship *);
extern struct ship *selectship();
extern void info(struct ship *);
extern UWORD weight(struct ship *);
extern UWORD freespace(struct ship *);
extern double speed(struct ship *);
extern void findslowest();
extern void setshipmoves(double);
extern void setshipfuel(UWORD);
extern void setshipfood(UWORD);
extern void consumefood();
extern UWORD getpay(struct ship *);
extern void checkships();
extern void moveship(BYTE, BYTE);
extern void setautocenter(UBYTE);
extern struct city *getcity(UBYTE);
extern void getcitylocation(struct city *, UWORD *, UWORD *);
extern void clearcitydiffs();
extern void citymap(struct RastPort *, UWORD, UWORD, UBYTE, UBYTE, UWORD,
    UWORD);
extern void gotocity(UBYTE);
extern void coordinatestrings(STRPTR, STRPTR, UWORD, UWORD);
extern UBYTE request(struct Window *, STRPTR, STRPTR, STRPTR, APTR);
extern void setmoney(ULONG);
extern void findslowest();
extern long rnd(long);
extern void cleartext();
extern void addtext(STRPTR);
extern void showtext();
extern void menuonoff(UBYTE, UBYTE, UBYTE);
extern void submenuonoff(UBYTE, UBYTE, UBYTE, UBYTE);
extern void showcargolist();
extern void makecargolist();
extern void freenodes();
extern void setdate(ULONG);
extern UWORD getblocktype(UWORD, UWORD);
extern UBYTE getrawblocktype(UWORD, UWORD);
extern void drawmap(WORD, WORD);
extern void transfer(struct ship *, struct ship *);
extern void writelog(STRPTR);
extern void writelogdate();
extern UWORD namesavailable[];
extern struct city *city;
extern void showcargostatus(UWORD, UWORD, UBYTE, UWORD, UWORD);
extern void showtransfervalues(UBYTE);
extern void selectfirstperson();
extern void autopilot();
