/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : JIPsoft (Joona I Palaste)
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_UL                                  0
#define GD_U                                   1
#define GD_UR                                  2
#define GD_L                                   3
#define GD_Center                              4
#define GD_R                                   5
#define GD_DL                                  6
#define GD_D                                   7
#define GD_DR                                  8
#define GD_Info                                9
#define GD_Dock                                10
#define GD_Ships                               11
#define GD_Moves                               12
#define GD_Fuel                                13
#define GD_Crew                                14
#define GD_Food                                15
#define GD_Date                                16
#define GD_Money                               17
#define GD_Latitude                            18
#define GD_Longitude                           19

#define GDX_UL                                 0
#define GDX_U                                  1
#define GDX_UR                                 2
#define GDX_L                                  3
#define GDX_Center                             4
#define GDX_R                                  5
#define GDX_DL                                 6
#define GDX_D                                  7
#define GDX_DR                                 8
#define GDX_Info                               9
#define GDX_Dock                               10
#define GDX_Ships                              11
#define GDX_Moves                              12
#define GDX_Fuel                               13
#define GDX_Crew                               14
#define GDX_Food                               15
#define GDX_Date                               16
#define GDX_Money                              17
#define GDX_Latitude                           18
#define GDX_Longitude                          19

#define GD_Name                                0
#define GD_Class                               1
#define GD_List                                2
#define GD_Docked                              3
#define GD_View                                4
#define GD_Release                             5
#define GD_Transfer                            6

#define GDX_Name                               0
#define GDX_Class                              1
#define GDX_List                               2
#define GDX_Docked                             3
#define GDX_View                               4
#define GDX_Release                            5
#define GDX_Transfer                           6

#define GD_Mode                                0
#define GD_Items                               1
#define GD_To                                  2
#define GD_Free                                3
#define GD_Ship                                4
#define GD_TransferOther                       5
#define GD_TransferThis                        6
#define GD_Amount                              7
#define GD_HowMuch                             8

#define GDX_Mode                               0
#define GDX_Items                              1
#define GDX_To                                 2
#define GDX_Free                               3
#define GDX_Ship                               4
#define GDX_TransferOther                      5
#define GDX_TransferThis                       6
#define GDX_Amount                             7
#define GDX_HowMuch                            8

#define GD_Welcome                             0
#define GD_Coordinates                         1
#define GD_CityDate                            2
#define GD_CityShip                            3
#define GD_Select                              4
#define GD_CityMoney                           5
#define GD_Sell                                6
#define GD_Buy                                 7
#define GD_Cargo                               8
#define GD_ViewCrew                            9
#define GD_ViewPassengers                      10
#define GD_Exit                                11
#define GD_BuySell                             12
#define GD_CityTransfer                        13

#define GDX_Welcome                            0
#define GDX_Coordinates                        1
#define GDX_CityDate                           2
#define GDX_CityShip                           3
#define GDX_Select                             4
#define GDX_CityMoney                          5
#define GDX_Sell                               6
#define GDX_Buy                                7
#define GDX_Cargo                              8
#define GDX_ViewCrew                           9
#define GDX_ViewPassengers                     10
#define GDX_Exit                               11
#define GDX_BuySell                            12
#define GDX_CityTransfer                       13

#define GD_CargoName                           0
#define GD_CargoShip                           1
#define GD_CargoAmount                         2
#define GD_CargoSpace                          3
#define GD_CargoCity                           4
#define GD_Price                               5
#define GD_CargoSupply                         6
#define GD_CargoDemand                         7
#define GD_CargoHowMuch                        8
#define GD_CargoBuy                            9
#define GD_CargoSell                           10

#define GDX_CargoName                          0
#define GDX_CargoShip                          1
#define GDX_CargoAmount                        2
#define GDX_CargoSpace                         3
#define GDX_CargoCity                          4
#define GDX_Price                              5
#define GDX_CargoSupply                        6
#define GDX_CargoDemand                        7
#define GDX_CargoHowMuch                       8
#define GDX_CargoBuy                           9
#define GDX_CargoSell                          10

#define GD_ShipClass                           0
#define GD_Weight                              1
#define GD_ShipCargo                           2
#define GD_Cabins                              3
#define GD_Docks                               4
#define GD_Speed                               5
#define GD_ShipPrice                           6
#define GD_ShipMoney                           7
#define GD_ShipBuy                             8
#define GD_Previous                            9
#define GD_Next                                10

#define GDX_ShipClass                          0
#define GDX_Weight                             1
#define GDX_ShipCargo                          2
#define GDX_Cabins                             3
#define GDX_Docks                              4
#define GDX_Speed                              5
#define GDX_ShipPrice                          6
#define GDX_ShipMoney                          7
#define GDX_ShipBuy                            8
#define GDX_Previous                           9
#define GDX_Next                               10

#define GD_SelectShip                          0

#define GDX_SelectShip                         0

#define GD_MapLatitude                         0
#define GD_MapLongitude                        1

#define GDX_MapLatitude                        0
#define GDX_MapLongitude                       1

#define GD_PeopleShip                          0
#define GD_ShipList                            1
#define GD_PeopleCity                          2
#define GD_CityList                            3
#define GD_Move                                4
#define GD_Text1                               5
#define GD_Text2                               6
#define GD_Text3                               7
#define GD_Text4                               8

#define GDX_PeopleShip                         0
#define GDX_ShipList                           1
#define GDX_PeopleCity                         2
#define GDX_CityList                           3
#define GDX_Move                               4
#define GDX_Text1                              5
#define GDX_Text2                              6
#define GDX_Text3                              7
#define GDX_Text4                              8

#define GD_LatDegrees                          0
#define GD_LatMinutes                          1
#define GD_NorthSouth                          2
#define GD_LonDegrees                          3
#define GD_LonMinutes                          4
#define GD_WestEast                            5
#define GD_City                                6
#define GD_OK                                  7

#define GDX_LatDegrees                         0
#define GDX_LatMinutes                         1
#define GDX_NorthSouth                         2
#define GDX_LonDegrees                         3
#define GDX_LonMinutes                         4
#define GDX_WestEast                           5
#define GDX_City                               6
#define GDX_OK                                 7

#define SeaTrade_CNT 20
#define Info_CNT 7
#define Transfer_CNT 9
#define City_CNT 14
#define Cargo_CNT 11
#define BuyShip_CNT 11
#define Select_CNT 1
#define Map_CNT 2
#define People_CNT 9
#define Autopilot_CNT 8

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern APTR                  VisualInfo;
extern struct Window        *SeaTradeWnd;
extern struct Window        *InfoWnd;
extern struct Window        *TransferWnd;
extern struct Window        *CityWnd;
extern struct Window        *CargoWnd;
extern struct Window        *BuyShipWnd;
extern struct Window        *SelectWnd;
extern struct Window        *MapWnd;
extern struct Window        *PeopleWnd;
extern struct Window        *AutopilotWnd;
extern struct Gadget        *SeaTradeGList;
extern struct Gadget        *InfoGList;
extern struct Gadget        *TransferGList;
extern struct Gadget        *CityGList;
extern struct Gadget        *CargoGList;
extern struct Gadget        *BuyShipGList;
extern struct Gadget        *SelectGList;
extern struct Gadget        *MapGList;
extern struct Gadget        *PeopleGList;
extern struct Gadget        *AutopilotGList;
extern struct Menu          *SeaTradeMenus;
extern struct IntuiMessage   SeaTradeMsg;
extern struct IntuiMessage   InfoMsg;
extern struct IntuiMessage   TransferMsg;
extern struct IntuiMessage   CityMsg;
extern struct IntuiMessage   CargoMsg;
extern struct IntuiMessage   BuyShipMsg;
extern struct IntuiMessage   SelectMsg;
extern struct IntuiMessage   MapMsg;
extern struct IntuiMessage   PeopleMsg;
extern struct IntuiMessage   AutopilotMsg;
extern struct Gadget        *SeaTradeGadgets[20];
extern struct Gadget        *InfoGadgets[7];
extern struct Gadget        *TransferGadgets[9];
extern struct Gadget        *CityGadgets[14];
extern struct Gadget        *CargoGadgets[11];
extern struct Gadget        *BuyShipGadgets[11];
extern struct Gadget        *SelectGadgets[1];
extern struct Gadget        *MapGadgets[2];
extern struct Gadget        *PeopleGadgets[9];
extern struct Gadget        *AutopilotGadgets[8];
extern UWORD                 SeaTradeLeft;
extern UWORD                 SeaTradeTop;
extern UWORD                 SeaTradeWidth;
extern UWORD                 SeaTradeHeight;
extern UWORD                 InfoLeft;
extern UWORD                 InfoTop;
extern UWORD                 InfoWidth;
extern UWORD                 InfoHeight;
extern UWORD                 TransferLeft;
extern UWORD                 TransferTop;
extern UWORD                 TransferWidth;
extern UWORD                 TransferHeight;
extern UWORD                 CityLeft;
extern UWORD                 CityTop;
extern UWORD                 CityWidth;
extern UWORD                 CityHeight;
extern UWORD                 CargoLeft;
extern UWORD                 CargoTop;
extern UWORD                 CargoWidth;
extern UWORD                 CargoHeight;
extern UWORD                 BuyShipLeft;
extern UWORD                 BuyShipTop;
extern UWORD                 BuyShipWidth;
extern UWORD                 BuyShipHeight;
extern UWORD                 SelectLeft;
extern UWORD                 SelectTop;
extern UWORD                 SelectWidth;
extern UWORD                 SelectHeight;
extern UWORD                 MapLeft;
extern UWORD                 MapTop;
extern UWORD                 MapWidth;
extern UWORD                 MapHeight;
extern UWORD                 PeopleLeft;
extern UWORD                 PeopleTop;
extern UWORD                 PeopleWidth;
extern UWORD                 PeopleHeight;
extern UWORD                 AutopilotLeft;
extern UWORD                 AutopilotTop;
extern UWORD                 AutopilotWidth;
extern UWORD                 AutopilotHeight;
extern UBYTE                *SeaTradeWdt;
extern UBYTE                 InfoWdt[];
extern UBYTE                *TransferWdt;
extern UBYTE                *CityWdt;
extern UBYTE                *CargoWdt;
extern UBYTE                *BuyShipWdt;
extern UBYTE                *SelectWdt;
extern UBYTE                *MapWdt;
extern UBYTE                *PeopleWdt;
extern UBYTE                *AutopilotWdt;
extern UBYTE                *View1Labels[];
extern UBYTE                *Mode2Labels[];
extern UBYTE                *Ship2Labels[];
extern UBYTE                *CargoName4Labels[];
extern UBYTE                *NorthSouth9Labels[];
extern UBYTE                *WestEast9Labels[];
extern struct MinList        Ships0List;
extern struct MinList        List1List;
extern struct MinList        Docked1List;
extern struct MinList        Items2List;
extern struct MinList        Cargo3List;
extern struct MinList        SelectShip6List;
extern struct MinList        ShipList8List;
extern struct MinList        CityList8List;
extern struct TextAttr       topaz8;
extern struct IntuiText      AutopilotIText[];
extern struct NewMenu        SeaTradeNewMenu[];
extern UWORD                 SeaTradeGTypes[];
extern UWORD                 InfoGTypes[];
extern UWORD                 TransferGTypes[];
extern UWORD                 CityGTypes[];
extern UWORD                 CargoGTypes[];
extern UWORD                 BuyShipGTypes[];
extern UWORD                 SelectGTypes[];
extern UWORD                 MapGTypes[];
extern UWORD                 PeopleGTypes[];
extern UWORD                 AutopilotGTypes[];
extern struct NewGadget      SeaTradeNGad[];
extern struct NewGadget      InfoNGad[];
extern struct NewGadget      TransferNGad[];
extern struct NewGadget      CityNGad[];
extern struct NewGadget      CargoNGad[];
extern struct NewGadget      BuyShipNGad[];
extern struct NewGadget      SelectNGad[];
extern struct NewGadget      MapNGad[];
extern struct NewGadget      PeopleNGad[];
extern struct NewGadget      AutopilotNGad[];
extern ULONG                 SeaTradeGTags[];
extern ULONG                 InfoGTags[];
extern ULONG                 TransferGTags[];
extern ULONG                 CityGTags[];
extern ULONG                 CargoGTags[];
extern ULONG                 BuyShipGTags[];
extern ULONG                 SelectGTags[];
extern ULONG                 MapGTags[];
extern ULONG                 PeopleGTags[];
extern ULONG                 AutopilotGTags[];
extern struct ColorSpec      ScreenColors[];
extern UWORD                 DriPens[];

extern int ULClicked( void );
extern int UClicked( void );
extern int URClicked( void );
extern int LClicked( void );
extern int CenterClicked( void );
extern int RClicked( void );
extern int DLClicked( void );
extern int DClicked( void );
extern int DRClicked( void );
extern int InfoClicked( void );
extern int DockClicked( void );
extern int ShipsClicked( void );
extern int NameClicked( void );
extern int ListClicked( void );
extern int DockedClicked( void );
extern int ViewClicked( void );
extern int ReleaseClicked( void );
extern int TransferClicked( void );
extern int ModeClicked( void );
extern int ItemsClicked( void );
extern int ShipClicked( void );
extern int TransferOtherClicked( void );
extern int TransferThisClicked( void );
extern int HowMuchClicked( void );
extern int SelectClicked( void );
extern int SellClicked( void );
extern int BuyClicked( void );
extern int CargoClicked( void );
extern int ViewCrewClicked( void );
extern int ViewPassengersClicked( void );
extern int ExitClicked( void );
extern int BuySellClicked( void );
extern int CityTransferClicked( void );
extern int CargoNameClicked( void );
extern int CargoHowMuchClicked( void );
extern int CargoBuyClicked( void );
extern int CargoSellClicked( void );
extern int ShipBuyClicked( void );
extern int PreviousClicked( void );
extern int NextClicked( void );
extern int SelectShipClicked( void );
extern int ShipListClicked( void );
extern int CityListClicked( void );
extern int MoveClicked( void );
extern int LatDegreesClicked( void );
extern int LatMinutesClicked( void );
extern int NorthSouthClicked( void );
extern int LonDegreesClicked( void );
extern int LonMinutesClicked( void );
extern int WestEastClicked( void );
extern int CityClicked( void );
extern int OKClicked( void );
extern int SeaTradeSave( void );
extern int SeaTradeAbout( void );
extern int SeaTradeQuit( void );
extern int SeaTradeNext( void );
extern int SeaTradePrevious( void );
extern int SeaTradeReleaseall( void );
extern int SeaTradeReleaseselect( void );
extern int SeaTradeAutopilot( void );
extern int SeaTradeNone( void );
extern int SeaTradeOffline( void );
extern int SeaTradeOnline( void );
extern int SeaTradeSkip( void );
extern int SeaTradeAlarms( void );
extern int SeaTradeLog( void );
extern int SeaTradeCloseLog( void );
extern int SeaTradeFastAutopilot( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void SeaTradeRender( void );
extern int HandleSeaTradeIDCMP( void );
extern int OpenSeaTradeWindow( void );
extern void CloseSeaTradeWindow( void );
extern void InfoRender( void );
extern int HandleInfoIDCMP( void );
extern int InfoCloseWindow();
extern int OpenInfoWindow( void );
extern void CloseInfoWindow( void );
extern int HandleTransferIDCMP( void );
extern int TransferCloseWindow();
extern int OpenTransferWindow( void );
extern void CloseTransferWindow( void );
extern void CityRender( void );
extern int HandleCityIDCMP( void );
extern int CityCloseWindow();
extern int OpenCityWindow( void );
extern void CloseCityWindow( void );
extern void CargoRender( void );
extern int HandleCargoIDCMP( void );
extern int CargoCloseWindow();
extern int OpenCargoWindow( void );
extern void CloseCargoWindow( void );
extern void BuyShipRender( void );
extern int HandleBuyShipIDCMP( void );
extern int BuyShipCloseWindow();
extern int OpenBuyShipWindow( void );
extern void CloseBuyShipWindow( void );
extern int HandleSelectIDCMP( void );
extern int SelectCloseWindow();
extern int OpenSelectWindow( void );
extern void CloseSelectWindow( void );
extern void MapRender( void );
extern int HandleMapIDCMP( void );
extern int MapCloseWindow();
extern int OpenMapWindow( void );
extern void CloseMapWindow( void );
extern void PeopleRender( void );
extern int HandlePeopleIDCMP( void );
extern int PeopleCloseWindow();
extern int OpenPeopleWindow( void );
extern void ClosePeopleWindow( void );
extern void AutopilotRender( void );
extern int HandleAutopilotIDCMP( void );
extern int AutopilotCloseWindow();
extern int OpenAutopilotWindow( void );
extern void CloseAutopilotWindow( void );

struct ship
{
    struct Node node;
    struct ship *next;
    struct ship *prev;
    struct ship *carrying[3];
    struct ship *carriedby;
    UBYTE name[13];
    UBYTE class;
    UBYTE location[3];
    UBYTE destination[3];
    UBYTE flags;
    UWORD cargo[12];
    UBYTE crew;
    UBYTE passengers;
    double moves;
    UWORD serialnumber;
};

struct class
{
    UBYTE name[12];
    UWORD weight;
    UWORD engine;
    UBYTE cabins;
    UWORD maxcargo;
    UBYTE docks;
    UWORD docksize;
    ULONG price;
};

struct city
{
    UBYTE name[8];
    UBYTE location[3];
    UBYTE type;
    UBYTE price[12];
    UBYTE shipsmade[14];
    UBYTE shipsavailable[56];
    UWORD supply[12];
    UWORD demand[12];
    struct ship store;
};

struct citystub
{
    UBYTE name[8];
    UBYTE location[3];
    UBYTE type;
    UBYTE price[12];
    UBYTE shipsmade[14];
    UBYTE shipsavailable[56];
};

struct person
{
    struct Node node;
    struct person *next;
    struct person *prev;
    UBYTE name[14];
    UBYTE source;
    UBYTE destination;
    UWORD flags;
    UWORD pay;
    ULONG deadline;
    void *location;
};

#define CREW 0 /* crew member */
#define TOURIST 1 /* passenger, not yet taken on ship */
#define PASSENGER 2 /* passenger, taken on ship (contract fixed) */
#define FAILED 3 /* player screwed up, passenger missed his/her deadline */

#define CONTRACTMARK 0x800 /* mark for persons who have recently become
                             passengers */
#define FAILMARK 0x1000 /* mark for passengers who have recently become failed
                           passengers */
#define LOCMASK 0xFE00
#define TYPEMASK 0xF9FF
#define MARKMASK 0xE7FF
